# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
#    - name: Use Node.js ${{ matrix.node-version }}
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
#        node-version: ${{ matrix.node-version }}
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_SERVER: ${{ secrets.MONGO_SERVER }}
          MONGO_DEFAULT_DATABASE: ${{ secrets.MONGO_DEFAULT_DATABASE }}
          MONGO_PROTOCOL: ${{ secrets.MONGO_PROTOCOL }}
          MONGO_PROPS: ${{ secrets.MONGO_USERNAME }}
          PORT: ${{ secrets.PORT }}
          MONGO_CONNECTIONSTRING: ${{ secrets.MONGO_CONNECTIONSTRING }}

